version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unused

  settings:
    goimports:
      local-prefixes:
        - github.com/krzhapps/GitTickets
